/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GraphSourceColorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// sourceDetector.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  sourceFolders: [],
  groupColors: {}
};
var SourceDetector = class {
  constructor(app, settings) {
    this.sourceCache = /* @__PURE__ */ new Map();
    // 源点出链指向的笔记 → 该笔记属于源点的子节点
    this.childMap = /* @__PURE__ */ new Map();
    this.app = app;
    this.settings = settings;
    this.buildSourceCache();
  }
  /**
   * 构建源点缓存
   * 文件夹下的所有文件自动成为源点，group = 文件夹路径
   */
  buildSourceCache() {
    this.sourceCache.clear();
    this.childMap.clear();
    const files = this.app.vault.getMarkdownFiles();
    const sourceFolders = this.settings.sourceFolders;
    for (const file of files) {
      let bestFolder = "";
      for (const folder of sourceFolders) {
        const prefix = folder.endsWith("/") ? folder : folder + "/";
        if (file.path.startsWith(prefix) || file.path === folder + ".md") {
          if (folder.length > bestFolder.length) {
            bestFolder = folder;
          }
        }
      }
      if (bestFolder) {
        this.sourceCache.set(file.path, {
          file,
          path: file.path,
          group: bestFolder,
          color: this.resolveFolderColor(bestFolder)
        });
      }
    }
    for (const [sourcePath, sourceInfo] of this.sourceCache) {
      const cache = this.app.metadataCache.getFileCache(sourceInfo.file);
      if (!(cache == null ? void 0 : cache.links))
        continue;
      for (const link of cache.links) {
        const resolved = this.app.metadataCache.getFirstLinkpathDest(link.link, sourcePath);
        if (!resolved)
          continue;
        const resolvedPath = resolved.path;
        if (this.sourceCache.has(resolvedPath))
          continue;
        if (!this.childMap.has(resolvedPath)) {
          this.childMap.set(resolvedPath, /* @__PURE__ */ new Set());
        }
        this.childMap.get(resolvedPath).add(sourcePath);
      }
    }
    const excludePaths = /* @__PURE__ */ new Set(["wiki/index.md"]);
    for (const file of files) {
      if (this.sourceCache.has(file.path))
        continue;
      if (excludePaths.has(file.path))
        continue;
      const cache = this.app.metadataCache.getFileCache(file);
      if (!(cache == null ? void 0 : cache.links))
        continue;
      for (const link of cache.links) {
        const resolved = this.app.metadataCache.getFirstLinkpathDest(link.link, file.path);
        if (!resolved)
          continue;
        if (!this.sourceCache.has(resolved.path))
          continue;
        if (!this.childMap.has(file.path)) {
          this.childMap.set(file.path, /* @__PURE__ */ new Set());
        }
        this.childMap.get(file.path).add(resolved.path);
      }
    }
    this.propagateSources();
  }
  /**
   * 沿 concept 之间的链接传播源点关系
   * BFS：已关联源点的节点，其出链指向的节点也继承该源点
   */
  propagateSources() {
    const queue = [];
    const visited = /* @__PURE__ */ new Set();
    for (const path of this.childMap.keys()) {
      queue.push(path);
      visited.add(path);
    }
    while (queue.length > 0) {
      const currentPath = queue.shift();
      const currentSources = this.childMap.get(currentPath);
      if (!currentSources || currentSources.size === 0)
        continue;
      const file = this.app.vault.getAbstractFileByPath(currentPath);
      if (!(file instanceof import_obsidian.TFile))
        continue;
      const cache = this.app.metadataCache.getFileCache(file);
      if (!(cache == null ? void 0 : cache.links))
        continue;
      for (const link of cache.links) {
        const resolved = this.app.metadataCache.getFirstLinkpathDest(link.link, currentPath);
        if (!resolved)
          continue;
        const resolvedPath = resolved.path;
        if (this.sourceCache.has(resolvedPath))
          continue;
        let changed = false;
        if (!this.childMap.has(resolvedPath)) {
          this.childMap.set(resolvedPath, /* @__PURE__ */ new Set());
        }
        const targetSources = this.childMap.get(resolvedPath);
        for (const sp of currentSources) {
          if (!targetSources.has(sp)) {
            targetSources.add(sp);
            changed = true;
          }
        }
        if (changed && !visited.has(resolvedPath)) {
          visited.add(resolvedPath);
          queue.push(resolvedPath);
        }
      }
    }
  }
  /**
   * 获取 group 对应的颜色
   */
  getGroupColor(group) {
    return this.settings.groupColors[group] || "";
  }
  /**
   * 解析文件夹颜色，含继承逻辑
   * 1. 如果 groupColors[folder] 有值 → 返回该值
   * 2. 否则向上查找父文件夹，递归继承
   * 3. 都没有 → 返回空串
   */
  resolveFolderColor(folder) {
    const color = this.settings.groupColors[folder];
    if (color)
      return color;
    const lastSlash = folder.lastIndexOf("/");
    if (lastSlash <= 0)
      return "";
    const parent = folder.substring(0, lastSlash);
    return this.resolveFolderColor(parent);
  }
  /**
   * 检查文件是否为源点
   */
  isSourceFile(file) {
    return this.sourceCache.has(file.path);
  }
  /**
   * 检查路径是否为源点
   */
  isSourcePath(path) {
    return this.sourceCache.has(path);
  }
  /**
   * 获取源点信息
   */
  getSourceInfo(path) {
    return this.sourceCache.get(path);
  }
  /**
   * 获取所有源点
   */
  getAllSources() {
    return Array.from(this.sourceCache.values());
  }
  /**
   * 更新设置
   */
  updateSettings(settings) {
    this.settings = settings;
    this.buildSourceCache();
  }
  /**
   * 获取笔记关联的所有源点
   */
  getLinkedSources(file) {
    const linkedSources = [];
    const sourcePaths = this.childMap.get(file.path);
    if (!sourcePaths)
      return linkedSources;
    for (const sourcePath of sourcePaths) {
      const sourceInfo = this.sourceCache.get(sourcePath);
      if (sourceInfo) {
        linkedSources.push(sourceInfo);
      }
    }
    return linkedSources;
  }
  /**
   * 通过路径获取关联的所有源点
   */
  getLinkedSourcesByPath(path) {
    const linkedSources = [];
    const sourcePaths = this.childMap.get(path);
    if (!sourcePaths)
      return linkedSources;
    for (const sourcePath of sourcePaths) {
      const sourceInfo = this.sourceCache.get(sourcePath);
      if (sourceInfo) {
        linkedSources.push(sourceInfo);
      }
    }
    return linkedSources;
  }
};

// colorManager.ts
var ColorManager = class {
  constructor(app, sourceDetector) {
    this.colorCache = /* @__PURE__ */ new Map();
    this.app = app;
    this.sourceDetector = sourceDetector;
  }
  /**
   * 清除缓存
   */
  clearCache() {
    this.colorCache.clear();
  }
  /**
   * 获取节点的颜色信息
   */
  getNodeColorInfo(path) {
    if (this.colorCache.has(path)) {
      return this.colorCache.get(path);
    }
    const sources = this.sourceDetector.getLinkedSourcesByPath(path);
    const colors = sources.map((s) => s.color);
    const info = {
      path,
      sources,
      colors
    };
    this.colorCache.set(path, info);
    return info;
  }
  /**
   * 获取节点应显示的颜色数组
   */
  getNodeColors(path) {
    const info = this.getNodeColorInfo(path);
    return info.colors;
  }
  /**
   * 刷新缓存
   */
  refresh() {
    this.sourceDetector.buildSourceCache();
    this.clearCache();
  }
};

// folderTreeSelector.ts
var import_obsidian2 = require("obsidian");
var FolderTreeSelector = class {
  constructor(app, containerEl, initialChecked) {
    this.tree = [];
    this.onCheckChange = () => {
    };
    this.app = app;
    this.containerEl = containerEl;
    this.checkedFolders = new Set(initialChecked);
    this.buildTree();
    this.render();
  }
  buildTree() {
    const root = this.app.vault.getRoot();
    this.tree = this.buildNodes(root);
  }
  buildNodes(parent) {
    const nodes = [];
    for (const child of parent.children) {
      if (child instanceof import_obsidian2.TFolder) {
        const node = {
          path: child.path,
          name: child.name,
          children: this.buildNodes(child),
          checked: this.checkedFolders.has(child.path),
          expanded: this.checkedFolders.has(child.path)
        };
        nodes.push(node);
      }
    }
    nodes.sort((a, b) => {
      if (a.children.length > 0 && b.children.length === 0)
        return -1;
      if (a.children.length === 0 && b.children.length > 0)
        return 1;
      return a.name.localeCompare(b.name);
    });
    return nodes;
  }
  render() {
    this.containerEl.empty();
    this.containerEl.addClass("folder-tree");
    for (const node of this.tree) {
      this.renderNode(node, this.containerEl);
    }
  }
  renderNode(node, container) {
    const item = container.createDiv({ cls: "folder-tree-item" });
    const row = item.createDiv({ cls: "folder-tree-row" });
    const toggle = row.createSpan({ cls: "folder-tree-toggle" });
    if (node.children.length > 0) {
      toggle.setText(node.expanded ? "\u25BE" : "\u25B8");
      toggle.addEventListener("click", () => {
        node.expanded = !node.expanded;
        toggle.setText(node.expanded ? "\u25BE" : "\u25B8");
        if (childContainer) {
          childContainer.style.display = node.expanded ? "block" : "none";
        }
      });
    } else {
      toggle.setText(" ");
      toggle.style.visibility = "hidden";
    }
    const checkbox = row.createEl("input", { type: "checkbox" });
    checkbox.addClass("folder-tree-checkbox");
    checkbox.checked = node.checked;
    checkbox.addEventListener("change", () => {
      node.checked = checkbox.checked;
      if (node.checked) {
        this.checkedFolders.add(node.path);
      } else {
        this.checkedFolders.delete(node.path);
      }
      this.onCheckChange(Array.from(this.checkedFolders));
    });
    row.createSpan({ text: node.name, cls: "folder-tree-name" });
    let childContainer = null;
    if (node.children.length > 0) {
      childContainer = item.createDiv({ cls: "folder-tree-children" });
      if (!node.expanded)
        childContainer.style.display = "none";
      for (const child of node.children) {
        this.renderNode(child, childContainer);
      }
    }
  }
};

// main.ts
var DEFAULT_SETTINGS2 = {
  ...DEFAULT_SETTINGS,
  enableMultiColor: true
};
var COLOR_PALETTE = [
  "#4A90D9",
  "#F5A623",
  "#7B68EE",
  "#50C878",
  "#FF6B6B",
  "#FFD93D",
  "#6BCB77",
  "#4D96FF",
  "#C084FC",
  "#FB923C",
  "#34D399",
  "#F472B6",
  "#60A5FA",
  "#A78BFA",
  "#38BDF8"
];
function getNextColor(existingColors) {
  for (const color of COLOR_PALETTE) {
    if (!existingColors.has(color))
      return color;
  }
  const hue = Math.floor(Math.random() * 360);
  return "#" + ((1 << 24) + (hue << 16) + (101 << 8) + 85).toString(16).slice(1);
}
var GraphSourceColorPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.overlayCanvases = /* @__PURE__ */ new Map();
    this.renderRAF = null;
    this.lastColorSync = 0;
    this.removing = false;
    this.obsidianColorMap = /* @__PURE__ */ new Map();
    this.nodeAlphaCache = /* @__PURE__ */ new Map();
    this.deletedPaths = /* @__PURE__ */ new Set();
  }
  async onload() {
    await this.loadSettings();
    this.app.workspace.onLayoutReady(async () => {
      this.removing = false;
      await this.migrateSettings();
      this.sourceDetector = new SourceDetector(this.app, this.settings);
      this.colorManager = new ColorManager(this.app, this.sourceDetector);
      console.log("[Graph Source Color] Initialized");
      await this.restoreColorsFromGraphJson();
      await this.loadObsidianColorMap();
      this.startOverlayRender();
    });
    this.registerEvent(
      this.app.metadataCache.on("changed", () => {
        if (this.colorManager)
          this.colorManager.refresh();
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        const deletedPath = file instanceof import_obsidian3.TFile ? file.path : "";
        if (deletedPath) {
          this.deletedPaths.add(deletedPath);
          this.nodeAlphaCache.delete(deletedPath);
        }
        setTimeout(() => {
          if (this.colorManager)
            this.colorManager.refresh();
          setTimeout(() => {
            if (this.colorManager)
              this.colorManager.refresh();
            if (deletedPath)
              this.deletedPaths.delete(deletedPath);
          }, 2e3);
        }, 500);
      })
    );
    this.registerEvent(
      this.app.vault.on("create", () => {
        if (this.colorManager)
          this.colorManager.refresh();
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        setTimeout(() => this.setupOverlays(), 500);
      })
    );
    this.addCommand({
      id: "refresh-graph-colors",
      name: "\u5237\u65B0\u56FE\u8C31\u989C\u8272 / Refresh Graph Colors",
      callback: () => {
        if (this.colorManager)
          this.colorManager.refresh();
        new import_obsidian3.Notice("\u56FE\u8C31\u989C\u8272\u5DF2\u5237\u65B0 / Graph colors refreshed");
      }
    });
    this.addCommand({
      id: "debug-graph-nodes",
      name: "\u8C03\u8BD5\u56FE\u8C31\u8282\u70B9 / Debug Graph Nodes",
      callback: () => this.debugGraphNodes()
    });
    this.addSettingTab(new GraphSourceColorSettingTab(this.app, this));
  }
  onunload() {
    this.removing = true;
    this.cleanupOverlay();
    console.log("[Graph Source Color] Unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS2, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.sourceDetector) {
      this.sourceDetector.updateSettings(this.settings);
    }
    if (this.colorManager) {
      this.colorManager.refresh();
    }
    if (!this.settings.enableMultiColor) {
      this.clearOverlaysAndRestoreNodes();
    } else {
      this.setupOverlays();
    }
  }
  async migrateSettings() {
    const loadedData = await this.loadData();
    if (!loadedData)
      return;
    let migrated = false;
    if (loadedData.sourceFolder !== void 0 && loadedData.sourceFolders === void 0) {
      const oldFolder = loadedData.sourceFolder;
      loadedData.sourceFolders = oldFolder ? [oldFolder] : [];
      delete loadedData.sourceFolder;
      migrated = true;
      const newGroupColors = {};
      for (const [oldGroup, color] of Object.entries(loadedData.groupColors || {})) {
        if (oldFolder) {
          const candidatePath = oldFolder + "/" + oldGroup;
          const exists = this.app.vault.getAbstractFileByPath(candidatePath) instanceof import_obsidian3.TFolder;
          if (exists) {
            newGroupColors[candidatePath] = color;
          } else if (!newGroupColors[oldFolder]) {
            newGroupColors[oldFolder] = color;
          }
        } else {
          newGroupColors[oldGroup] = color;
        }
      }
      if (oldFolder && !newGroupColors[oldFolder]) {
        newGroupColors[oldFolder] = "#4A90D9";
      }
      loadedData.groupColors = newGroupColors;
    }
    if (migrated) {
      await this.saveData(loadedData);
      this.settings = Object.assign({}, DEFAULT_SETTINGS2, loadedData);
    }
  }
  async restoreColorsFromGraphJson() {
    var _a, _b, _c, _d, _e;
    if (!this.sourceDetector)
      return;
    try {
      const existingGroups = (_a = await this.readExistingColorGroups()) != null ? _a : [];
      if (existingGroups.length === 0)
        return;
      for (const cg of existingGroups) {
        if (!((_b = cg.query) == null ? void 0 : _b.startsWith("path:")))
          continue;
        if (((_c = cg.color) == null ? void 0 : _c.rgb) === void 0 || ((_d = cg.color) == null ? void 0 : _d.rgb) === 0 || ((_e = cg.color) == null ? void 0 : _e.rgb) === 16777215)
          continue;
        const queryPath = cg.query.replace("path:", "");
        if (this.settings.sourceFolders.includes(queryPath)) {
          const color = "#" + cg.color.rgb.toString(16).padStart(6, "0");
          if (color !== "#000000" && color !== "#ffffff") {
            this.settings.groupColors[queryPath] = color;
          }
        }
      }
      this.sourceDetector.updateSettings(this.settings);
      this.saveData(this.settings);
    } catch (e) {
      console.warn("[Graph Source Color] Failed to restore colors from graph.json", e);
    }
  }
  async readExistingColorGroups() {
    try {
      const adapter = this.app.vault.adapter;
      const graphJsonPath = this.app.vault.configDir + "/graph.json";
      if (!await adapter.exists(graphJsonPath))
        return null;
      const raw = await adapter.read(graphJsonPath);
      const config = JSON.parse(raw);
      const groups = config.colorGroups;
      if (!Array.isArray(groups))
        return null;
      return groups;
    } catch (e) {
      return null;
    }
  }
  async loadObsidianColorMap() {
    var _a, _b, _c;
    const newMap = /* @__PURE__ */ new Map();
    const groups = await this.readExistingColorGroups();
    if (!groups) {
      this.obsidianColorMap = newMap;
      return;
    }
    for (const cg of groups) {
      if (!cg.query)
        continue;
      if (((_a = cg.color) == null ? void 0 : _a.rgb) === void 0 || ((_b = cg.color) == null ? void 0 : _b.rgb) === 0 || ((_c = cg.color) == null ? void 0 : _c.rgb) === 16777215)
        continue;
      const color = "#" + cg.color.rgb.toString(16).padStart(6, "0");
      if (color === "#000000" || color === "#ffffff")
        continue;
      const pathMatch = cg.query.match(/^path:(\S+)/);
      if (!pathMatch)
        continue;
      const pathPart = pathMatch[1];
      const fileMatch = cg.query.match(/\bfile:(\S+)/);
      if (fileMatch) {
        const filePath = pathPart + "/" + fileMatch[1] + ".md";
        newMap.set(filePath, color);
      } else {
        newMap.set(pathPart, color);
      }
    }
    this.obsidianColorMap = newMap;
  }
  hasObsidianColorGroup(path) {
    for (const groupPath of this.obsidianColorMap.keys()) {
      if (path === groupPath)
        return true;
      if (path === groupPath + ".md")
        return true;
      if (path.endsWith(".md") && path.slice(0, -3) === groupPath)
        return true;
      const prefix = groupPath.endsWith("/") ? groupPath : groupPath + "/";
      if (path.startsWith(prefix))
        return true;
    }
    return false;
  }
  getObsidianColor(path) {
    for (const [groupPath, color] of this.obsidianColorMap) {
      if (path === groupPath)
        return color;
      if (path === groupPath + ".md")
        return color;
      if (path.endsWith(".md") && path.slice(0, -3) === groupPath)
        return color;
    }
    return void 0;
  }
  getEffectiveSourceColor(sourcePath) {
    var _a;
    const obsColor = this.getObsidianColor(sourcePath);
    if (obsColor)
      return obsColor;
    const sourceInfo = (_a = this.sourceDetector) == null ? void 0 : _a.getSourceInfo(sourcePath);
    return (sourceInfo == null ? void 0 : sourceInfo.color) || void 0;
  }
  getChildNodeColors(nodeId) {
    if (!this.sourceDetector || !this.colorManager)
      return [];
    const info = this.colorManager.getNodeColorInfo(nodeId);
    if (!info || info.sources.length === 0)
      return [];
    const colorSet = [];
    const seenColors = /* @__PURE__ */ new Set();
    for (const source of info.sources) {
      const color = this.getEffectiveSourceColor(source.path);
      if (color && !seenColors.has(color)) {
        seenColors.add(color);
        colorSet.push(color);
      }
    }
    return colorSet;
  }
  syncColorsFromRenderer() {
    this.loadObsidianColorMap();
    return false;
  }
  getNodeScreenPos(node, scale, panX, panY, nodeScale) {
    if (node.circle && typeof node.circle.getBounds === "function") {
      const bounds = node.circle.getBounds();
      return {
        x: bounds.x + bounds.width / 2,
        y: bounds.y + bounds.height / 2,
        r: bounds.width / 2
      };
    }
    return {
      x: node.x * scale + panX,
      y: node.y * scale + panY,
      r: 3 * nodeScale * scale
    };
  }
  getNodeAlpha(nodeId, currentAlpha) {
    var _a;
    if (currentAlpha > 0) {
      this.nodeAlphaCache.set(nodeId, currentAlpha);
    }
    return (_a = this.nodeAlphaCache.get(nodeId)) != null ? _a : 1;
  }
  releaseNodeAlpha(nodeId) {
    this.nodeAlphaCache.delete(nodeId);
  }
  isNodeAlive(nodeId) {
    if (this.deletedPaths.has(nodeId))
      return false;
    return !!this.app.vault.getAbstractFileByPath(nodeId);
  }
  // --- Canvas Overlay ---
  setupOverlays() {
    for (const viewType of ["graph", "localgraph"]) {
      this.app.workspace.getLeavesOfType(viewType).forEach((leaf) => {
        var _a;
        const view = leaf.view;
        const containerEl = view.contentEl;
        if (!containerEl)
          return;
        const key = (_a = leaf.id) != null ? _a : "";
        if (this.overlayCanvases.has(key)) {
          const existing = this.overlayCanvases.get(key);
          if (existing.isConnected)
            return;
          existing.remove();
          this.overlayCanvases.delete(key);
        }
        const canvas = document.createElement("canvas");
        canvas.style.position = "absolute";
        canvas.style.top = "0";
        canvas.style.left = "0";
        canvas.style.width = "100%";
        canvas.style.height = "100%";
        canvas.style.pointerEvents = "none";
        canvas.style.zIndex = "10";
        canvas.className = "graph-source-color-overlay";
        containerEl.style.position = "relative";
        containerEl.appendChild(canvas);
        this.overlayCanvases.set(key, canvas);
        const syncSize = () => {
          var _a2, _b, _c;
          const r = (_b = (_a2 = leaf.view) == null ? void 0 : _a2.dataEngine) == null ? void 0 : _b.renderer;
          const pxRenderer = (_c = r == null ? void 0 : r.px) == null ? void 0 : _c.renderer;
          if (pxRenderer) {
            canvas.width = pxRenderer.width;
            canvas.height = pxRenderer.height;
          } else {
            canvas.width = containerEl.clientWidth;
            canvas.height = containerEl.clientHeight;
          }
        };
        syncSize();
        const ro = new ResizeObserver(() => syncSize());
        ro.observe(containerEl);
        this.register(() => ro.disconnect());
      });
    }
  }
  cleanupOverlay() {
    this.removing = true;
    if (this.renderRAF) {
      cancelAnimationFrame(this.renderRAF);
      this.renderRAF = null;
    }
    this.clearOverlaysAndRestoreNodes();
  }
  clearOverlaysAndRestoreNodes() {
    this.overlayCanvases.forEach((canvas) => {
      const ctx = canvas.getContext("2d");
      if (ctx)
        ctx.clearRect(0, 0, canvas.width, canvas.height);
      canvas.style.display = "none";
      if (canvas.parentNode)
        canvas.parentNode.removeChild(canvas);
    });
    this.overlayCanvases.clear();
    document.querySelectorAll(".graph-source-color-overlay").forEach((el) => el.remove());
    for (const viewType of ["graph", "localgraph"]) {
      this.app.workspace.getLeavesOfType(viewType).forEach((leaf) => {
        var _a;
        const view = leaf.view;
        const containerEl = view.contentEl;
        const renderer = (_a = view.dataEngine) == null ? void 0 : _a.renderer;
        if (!containerEl)
          return;
        containerEl.querySelectorAll("canvas").forEach((canvas) => {
          const el = canvas;
          if (el.style.pointerEvents === "none" && el.style.zIndex === "10") {
            const ctx = canvas.getContext("2d");
            if (ctx)
              ctx.clearRect(0, 0, canvas.width, canvas.height);
            el.style.display = "none";
            if (canvas.parentNode)
              canvas.parentNode.removeChild(canvas);
          }
        });
        if (!(renderer == null ? void 0 : renderer.nodes))
          return;
        for (const node of renderer.nodes) {
          if (node.id && node.circle && node.circle.alpha === 0) {
            node.circle.alpha = 1;
          }
        }
      });
    }
  }
  startOverlayRender() {
    this.setupOverlays();
    const renderLoop = () => {
      if (this.removing)
        return;
      try {
        this.renderOverlayNodes();
      } catch (e) {
        console.warn("[Graph Source Color] Render loop error:", e);
      }
      this.renderRAF = requestAnimationFrame(renderLoop);
    };
    this.renderRAF = requestAnimationFrame(renderLoop);
  }
  renderOverlayNodes() {
    if (!this.colorManager || !this.settings.enableMultiColor)
      return;
    const now = Date.now();
    if (now - this.lastColorSync > 2e3) {
      this.syncColorsFromRenderer();
      this.lastColorSync = now;
    }
    for (const viewType of ["graph", "localgraph"]) {
      this.app.workspace.getLeavesOfType(viewType).forEach((leaf) => {
        var _a, _b, _c, _d, _e;
        try {
          const view = leaf.view;
          const dataEngine = view.dataEngine;
          const renderer = dataEngine == null ? void 0 : dataEngine.renderer;
          if (!(renderer == null ? void 0 : renderer.nodes))
            return;
          const key = (_a = leaf.id) != null ? _a : "";
          const canvas = this.overlayCanvases.get(key);
          if (!canvas)
            return;
          const ctx = canvas.getContext("2d");
          if (!ctx)
            return;
          const pxRenderer = (_b = renderer.px) == null ? void 0 : _b.renderer;
          if (pxRenderer) {
            const pw = pxRenderer.width;
            const ph = pxRenderer.height;
            if (canvas.width !== pw || canvas.height !== ph) {
              canvas.width = pw;
              canvas.height = ph;
            }
          }
          ctx.clearRect(0, 0, canvas.width, canvas.height);
          const scale = renderer.scale || 1;
          const panX = renderer.panX || 0;
          const panY = renderer.panY || 0;
          const nodeScale = renderer.nodeScale || 1;
          for (const node of renderer.nodes) {
            try {
              if (!node.id)
                continue;
              if (!this.isNodeAlive(node.id)) {
                if (node.circle && node.circle.alpha === 0)
                  node.circle.alpha = 1;
                this.releaseNodeAlpha(node.id);
                continue;
              }
              const currentAlpha = (_d = (_c = node.circle) == null ? void 0 : _c.alpha) != null ? _d : 1;
              const nodeAlpha = this.getNodeAlpha(node.id, currentAlpha);
              if ((_e = this.sourceDetector) == null ? void 0 : _e.isSourcePath(node.id)) {
                if (this.hasObsidianColorGroup(node.id)) {
                  if (node.circle && node.circle.alpha === 0)
                    node.circle.alpha = 1;
                  this.releaseNodeAlpha(node.id);
                  continue;
                }
                const folderColor = this.getEffectiveSourceColor(node.id);
                if (!folderColor) {
                  if (node.circle && node.circle.alpha === 0)
                    node.circle.alpha = 1;
                  this.releaseNodeAlpha(node.id);
                  continue;
                }
                if (node.circle)
                  node.circle.alpha = 0;
                const pos2 = this.getNodeScreenPos(node, scale, panX, panY, nodeScale);
                this.drawSingleColorNode(ctx, pos2.x, pos2.y, pos2.r, folderColor, nodeAlpha);
                continue;
              }
              if (this.hasObsidianColorGroup(node.id)) {
                if (node.circle && node.circle.alpha === 0)
                  node.circle.alpha = 1;
                this.releaseNodeAlpha(node.id);
                continue;
              }
              const colors = this.getChildNodeColors(node.id);
              if (colors.length === 0) {
                if (node.circle && node.circle.alpha === 0)
                  node.circle.alpha = 1;
                this.releaseNodeAlpha(node.id);
                continue;
              }
              const pos = this.getNodeScreenPos(node, scale, panX, panY, nodeScale);
              if (node.circle)
                node.circle.alpha = 0;
              if (colors.length === 1) {
                this.drawSingleColorNode(ctx, pos.x, pos.y, pos.r, colors[0], nodeAlpha);
              } else {
                this.drawMultiColorNode(ctx, pos.x, pos.y, pos.r, colors, nodeAlpha);
              }
            } catch (e) {
              try {
                if ((node == null ? void 0 : node.circle) && node.circle.alpha === 0)
                  node.circle.alpha = 1;
              } catch (e2) {
              }
            }
          }
        } catch (e) {
          console.warn("[Graph Source Color] View render error:", e);
        }
      });
    }
  }
  drawSingleColorNode(ctx, x, y, radius, color, alpha) {
    ctx.globalAlpha = alpha;
    ctx.beginPath();
    ctx.arc(x, y, radius, 0, 2 * Math.PI);
    ctx.fillStyle = color;
    ctx.fill();
    ctx.strokeStyle = "#333333";
    ctx.lineWidth = 1;
    ctx.stroke();
    ctx.globalAlpha = 1;
  }
  drawMultiColorNode(ctx, x, y, radius, colors, alpha) {
    ctx.globalAlpha = alpha;
    if (colors.length === 2) {
      ctx.beginPath();
      ctx.arc(x, y, radius, Math.PI / 2, 3 * Math.PI / 2);
      ctx.fillStyle = colors[0];
      ctx.fill();
      ctx.beginPath();
      ctx.arc(x, y, radius, -Math.PI / 2, Math.PI / 2);
      ctx.fillStyle = colors[1];
      ctx.fill();
    } else {
      const sliceAngle = 2 * Math.PI / colors.length;
      colors.forEach((color, i) => {
        const startAngle = -Math.PI / 2 + i * sliceAngle;
        const endAngle = startAngle + sliceAngle;
        ctx.beginPath();
        ctx.moveTo(x, y);
        ctx.arc(x, y, radius, startAngle, endAngle);
        ctx.closePath();
        ctx.fillStyle = color;
        ctx.fill();
      });
    }
    ctx.beginPath();
    ctx.arc(x, y, radius, 0, 2 * Math.PI);
    ctx.strokeStyle = "#333333";
    ctx.lineWidth = 1;
    ctx.stroke();
    ctx.globalAlpha = 1;
  }
  // --- Debug ---
  debugGraphNodes() {
    var _a;
    console.log("=== Graph Source Color Debug ===");
    console.log("Settings:", JSON.stringify(this.settings, null, 2));
    console.log("Obsidian colorGroups:", Object.fromEntries(this.obsidianColorMap));
    console.log("Deleted paths:", Array.from(this.deletedPaths));
    if (this.colorManager) {
      const files = this.app.vault.getMarkdownFiles();
      for (const file of files) {
        if ((_a = this.sourceDetector) == null ? void 0 : _a.isSourcePath(file.path)) {
          const effectiveColor = this.getEffectiveSourceColor(file.path);
          const hasObsidian = this.hasObsidianColorGroup(file.path);
          console.log(`  [SOURCE] "${file.path}": effectiveColor=${effectiveColor}, obsidianSet=${hasObsidian}`);
        } else {
          const colors = this.getChildNodeColors(file.path);
          if (colors.length > 0) {
            const tag = colors.length > 1 ? "MULTI" : "single";
            console.log(`  [${tag}] "${file.path}": colors=${JSON.stringify(colors)}`);
          }
        }
      }
    }
    for (const [key, canvas] of this.overlayCanvases) {
      console.log(`Overlay canvas "${key}": ${canvas.width}x${canvas.height}`);
    }
    new import_obsidian3.Notice("\u8C03\u8BD5\u4FE1\u606F\u5DF2\u8F93\u51FA\u5230\u63A7\u5236\u53F0 / Debug info output to console");
  }
};
var GraphSourceColorSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u56FE\u8C31\u6E90\u70B9\u7740\u8272\u8BBE\u7F6E / Graph Source Color Settings" });
    new import_obsidian3.Setting(containerEl).setName("\u542F\u7528\u591A\u8272\u8282\u70B9 / Enable Multi-Color Nodes").setDesc("\u4E3A\u94FE\u63A5\u591A\u4E2A\u6E90\u70B9\u7684\u7B14\u8BB0\u663E\u793A\u591A\u8272\u8282\u70B9 / Show split-color nodes for notes linked to multiple sources").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableMultiColor).onChange(async (value) => {
      this.plugin.settings.enableMultiColor = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u6E90\u70B9\u6587\u4EF6\u5939 / Source Folders" });
    containerEl.createEl("p", {
      text: "\u9009\u62E9\u5305\u542B\u6E90\u70B9\u7B14\u8BB0\u7684\u6587\u4EF6\u5939\uFF0C\u6BCF\u4E2A\u6587\u4EF6\u5939\u5BF9\u5E94\u4E00\u79CD\u989C\u8272\u5206\u7EC4 / Select folders containing source notes, each folder maps to one color group",
      cls: "setting-item-description"
    });
    const treeContainer = containerEl.createDiv({ cls: "folder-tree-container" });
    const treeSelector = new FolderTreeSelector(this.app, treeContainer, this.plugin.settings.sourceFolders);
    treeSelector.onCheckChange = async (checkedFolders) => {
      this.plugin.settings.sourceFolders = checkedFolders;
      for (const folder of checkedFolders) {
        if (!this.plugin.settings.groupColors[folder]) {
          const usedColors = new Set(Object.values(this.plugin.settings.groupColors));
          this.plugin.settings.groupColors[folder] = getNextColor(usedColors);
        }
      }
      await this.plugin.saveSettings();
      this.display();
    };
    containerEl.createEl("h3", { text: "\u5206\u7EC4\u989C\u8272 / Group Colors" });
    containerEl.createEl("p", {
      text: "\u4E3A\u6E90\u70B9\u6587\u4EF6\u5939\u8BBE\u7F6E\u989C\u8272\uFF0C\u6E90\u70B9\u8282\u70B9\u548C\u5B50\u8282\u70B9\u90FD\u4F1A\u4F7F\u7528\u5BF9\u5E94\u989C\u8272 / Set colors for source folders, both source and child nodes will use the assigned color",
      cls: "setting-item-description"
    });
    for (const folder of this.plugin.settings.sourceFolders) {
      const color = this.plugin.settings.groupColors[folder] || "#4A90D9";
      new import_obsidian3.Setting(containerEl).setName(folder).addColorPicker((picker) => picker.setValue(color).onChange(async (value) => {
        this.plugin.settings.groupColors[folder] = value;
        await this.plugin.saveSettings();
      }));
    }
  }
};

/* nosourcemap */